### PR TITLE
Latest Amazon Linux 2 stack with Nodejs 14 for Meteor 2.3+

### PR DESCRIPTION
**Pull request by s7dhansh**
Latest Amazon Linux 2 stack with Nodejs 14 for Meteor 2.3+

### CODE REVIEW

**Comment by jamauro** [comment]
Unfortunately, I don't think this suggest change would work. A potential solution could be to include the top level node version as a variable in `mup.js` and then use that to do something like 
```SolutionStacks.find(name => name.endsWith(`running Node.js ${NODE_VERSION}`))```;

Actually might even be better to look at the Meteor Node version used so that you wouldn't need to have a configurable variable. It would just work.

**Comment by s7dhansh** [comment]
@jamauro while I like your idea, the changes work. I am using the same in https://github.com/settlin/mup-aws-beanstalk/ along with some extra features and using it to deploy my Meteor 2.3+ apps successfully.

**Comment by jamauro** [comment]
Ok cool. I tried just console.logging `SolutionStacks` and saw that the order for Node.js did not have the latest version first so   I wasn't sure if we could always depend on the array order.

**Comment by jamauro** [comment]
> Actually might even be better to look at the Meteor Node version used so that you wouldn't need to have a configurable variable. It would just work.

Proposing a solution like this here: https://github.com/zodern/mup-aws-beanstalk/pull/133

**Comment by zodern** [comment]
Thanks @s7dhansh. I implemented it using the [platform arn instead of solution stack](https://github.com/zodern/mup-aws-beanstalk/commit/5b7605b05ef59643e8e75d63b422068175e8dcfb) since it allows us to filter to get the one we want.

**Comment by zodern** [comment]
There is a beta if you want to try it (#142). There were many changes since with Amazon Linux 2 the hooks and deploy process is different.

**Pull request closed without merging**
