### PR TITLE
added secure http headers and general nginx security hardening

### PR DESCRIPTION
**Pull request by fschaeffler**
Most changes in this PR were done for security hardening of the Nginx and its connections. This is needed in order to comply with [PCI-DSS](https://en.wikipedia.org/wiki/Payment_Card_Industry_Data_Security_Standard), as well as a preparation for [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation), which will get enforced on 25th of May 2018.

With this PR, the following changes have been done.

- added configurable DNS-resolver for the Nginx-config, which defaults to the AWS VPC's standard DNS-server at the IP-address x.x.x.2
- added the following configurable secure HTTP headers to the Nginx-config
  - Strict-Transport-Security
  - X-Frame-Options
  - X-Content-Type-Options
  - X-XSS-Protection
  - X-Robots-Tag
  - Content-Security-Policy
- fixed the health-check due to a redirect (#38)
- added a failsafe for the start of the health-check-server
- added a backup-port for the health-check-server
- updated `npm run lint` to run `prepare` and `build` before a test-run

### CODE REVIEW

**Comment by iamfeek** [comment]
This change looks awesome. Thanks @fschaeffler !!

**Comment by fschaeffler** [comment]
@zodern I just merged the latest changes from master into the feature-branch. Is there any thoughts on whether those changes here are wanted  / needed? If not, I'll close this PR and won't proceed any further with it.

**Comment by fschaeffler** [comment]
@zodern it seems there's no need for GDPR / PCI compliance within zodern/mup-aws-beanstalk so I'll close this PR next Monday (21.05.2018).

**Comment by zodern** [comment]
@fschaeffler sorry for not looking at it sooner. Thanks for working on this.

> added the following configurable secure HTTP headers to the Nginx-config

I like this change. I would like it if it could accept any header instead of limiting it. Another option is to allow customizing the nginx config, similar to how it is done in [Meteor Up](http://meteor-up.com/docs#custom-nginx-config).

> added a backup-port for the health-check-server

This is a nice improvement, but I am not sure it would work correctly since the process using port `8039` could respond to the requests, preventing the health check server on port 8049 from handling them.

The other changes all look good. If you are still interested in getting this merged, I will do a more thorough review of the code.

**Comment by tigrente** [comment]
Is custom NGINX configuration possible?  I would like to use this not only for hardening but to add areas of basic authentication to public directories.  I did this with MUP, but doesn't seem possible with Beanstalk.

**Pull request closed without merging**
